server:
  port: 8099

logging:
  level:
    root: INFO
  
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  datasource:
    url: jdbc:mysql://dev.mysqldb:3306/sky_line_db_wuling?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Aispeech!@#321
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate.enable_lazy_load_no_trans: true
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: custom-client-id
            client-secret: custom-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/custom
            scope: read,foo
        provider:
          custom:
            authorization-uri: http://localhost:8081/spring-security-oauth-server/oauth/authorize
            token-uri: http://localhost:8081/spring-security-oauth-server/oauth/token
            user-info-uri: http://localhost:8088/spring-security-oauth-resource/users/extra
            user-name-attribute: user_name
security:
  oauth2:
    authorization:
      jwt:
        key-store: classpath:keystore.jks
        key-store-password: aispeech123
        key-alias: wisely
        key-password: aispeech123
                 
eureka:
  client:
    service-url:
      defaultZone: http://dev.eureka.server:8761/eureka/