server:
  port: 8099

logging:
  level:
    root: info
  
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  datasource:
    url: jdbc:mysql://dev.mysqldb:3306/sky_line_db_wuling?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Aispeech!@#321
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate.enable_lazy_load_no_trans: true
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: Aispeech
            client-secret: Aispeech123!
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8099/login/oauth2/code/custom
            scope: read
        provider:
          custom:
            authorization-uri: http://localhost:8769/oauth/authorize
            token-uri: http://localhost:8769/oauth/token
            user-info-uri: http://localhost:8769/oauth/token_key
            user-name-attribute: alg
               
eureka:
  client:
    service-url:
      defaultZone: http://dev.eureka.server:8761/eureka/