server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://dev.eureka.server:8761/eureka/
spring:
  application:
    name: service-hi
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://service-gateway:8099/.well-known/jwks.json