server:
  port: 8762

logging:
  level:
    root: info
    org.apache.coyote.http11.Http11InputBuffer: ${HTTP_LOG_LEVEL:INFO}

eureka:
  client:
    serviceUrl:
      defaultZone: http://dev.eureka.server:8761/eureka/
spring:
  application:
    name: service-hi
  cloud.loadbalancer.ribbon.enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://oauth-server:8769/.auth/jwks.json