server:
  port: 8769

logging:
  level:
    root: info
    org.apache.coyote.http11.Http11InputBuffer: ${HTTP_LOG_LEVEL:INFO}

eureka:
  client:
    serviceUrl:
      defaultZone: http://dev.eureka.server:8761/eureka/

spring:
  application:
    name: oauth-server
  cloud.loadbalancer.ribbon.enabled: false
  datasource:
    url: jdbc:mysql://dev.mysqldb:3306/sky_line_db_wuling?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Aispeech!@#321
    driver-class-name: com.mysql.cj.jdbc.Driver

security:
  oauth2:
    authorization:
      jwt:
        key-store: classpath:keystore.jks
        key-store-password: aispeech123
        key-alias: wisely
        key-password: aispeech123
      token-key-access: permitAll()
      check-token-access: isAuthenticated()
    client:
      client-id: Aispeech
      client-secret: Aispeech123!
      authorized-grant-types:
      - authorization_code
      registered-redirect-uri:
      - http://localhost:8099/login/oauth2/code/custom
      scope:
      - read
      
    
    