server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://dev.eureka.server:8761/eureka/
spring:
  application:
    name: service-feign
    
feign:
  hystrix:
    enabled: true